name: Docker image

on:
  push:
    branches: [canary]

permissions:
  packages: write

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: oskardotglobal
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push base
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ghcr.io/oskardotglobal/dos-api:latest
